image: gcc

before_script:
  - apt-get update && apt-get -y install cmake

build-job:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make


test-job1:
  stage: test
  script:
    - ctest --verbose

